name: basic_etl
inputs:
  - path: data.csv
    format: csv

steps:
  - type: select
    columns:
      - id
      - name
      - age
      - city
  - type: filter
    condition: "age >= 18"

outputs:
  - path: output.parquet
    format: parquet
