name: data_validation
inputs:
  - path: dirty_data.csv
    format: csv

steps:
  - type: validate
    checks:
      columns:
        - name: email
          unique: true
        - name: age
          range: [0, 120]
        - name: user_type
          not_null: true
    mode: quarantine

outputs:
  - path: clean_output.parquet
    format: parquet
